#!/usr/bin/env python3
"""Regenerate tests/fixtures/peg-morphology-diff.md deterministically.

Inputs: a local mirror of mw.lojban.org (WIKI_MIRROR, default ~/git/lojban-wiki)
and an ilmentufa checkout (ILMENTUFA_DIR). Method, exactly:
1. Wiki side: take the wikitext of "BPFK Section: PEG Morphology Algorithm";
   keep lines containing "<-" that are not comments (leading ";"); strip
   trailing "%%%" and ilmentufa "#: <node-type>" annotations; normalize "-" to "_" in rule names/bodies and collapse
   whitespace runs to single spaces.
2. ilmentufa side: take camxes.peg lines containing "<-" from the morphology
   region (the rules after the syntax section), same normalization minus the
   dash step (already underscored).
3. Join on rule name; report every rule present in BOTH whose normalized
   bodies differ, sorted by name. Rules present on only one side are listed
   separately (these include the wiki page's cmavo-classification section and
   ilmentufa's implementation-specific additions; they are inventory
   differences, not rule-body drift).
"""
import json, os, re, subprocess, sys

WIKI = os.path.expanduser(os.environ.get("WIKI_MIRROR", "~/git/lojban-wiki"))
ILM = os.path.expanduser(os.environ.get("ILMENTUFA_DIR", "~/git/ilmentufa"))

idx = json.load(open(f"{WIKI}/pages/index.json"))
page = next(p for p in idx if p["title"] == "BPFK Section: PEG Morphology Algorithm")
wiki_src = open(f"{WIKI}/{page['source']}").read()
snap = json.load(open(f"{WIKI}/snapshot.json"))
ilm_head = subprocess.run(["git", "-C", ILM, "rev-parse", "HEAD"],
                          capture_output=True, text=True).stdout.strip()

def norm_rules(lines, dashes=False):
    rules = {}
    for ln in lines:
        ln = ln.replace("%%%", "").strip()
        ln = re.sub(r"#:.*$", "", ln).strip()   # strip ilmentufa node-type annotations
        if "<-" not in ln or ln.startswith(";") or ln.startswith("#"):
            continue
        if dashes:
            ln = ln.replace("-", "_")
        ln = re.sub(r"\s+", " ", ln).strip()
        name, _, body = ln.partition("<_ ") if "<_ " in ln else ln.partition("<- ")
        name = name.strip()
        if name and body:
            rules[name] = body.strip()
    return rules

wiki_rules = norm_rules(wiki_src.split("\n"), dashes=True)
ilm_rules = norm_rules(open(f"{ILM}/camxes.peg").read().split("\n"))

# The wiki page also carries a cmavo-classification section (selma'o rules,
# UPPERCASE names) that has no counterpart in ilmentufa's morphology region;
# the join below handles that naturally.
both = sorted(set(wiki_rules) & set(ilm_rules))
diff = [(n, wiki_rules[n], ilm_rules[n]) for n in both if wiki_rules[n] != ilm_rules[n]]
only_wiki = sorted(set(wiki_rules) - set(ilm_rules))
only_ilm = sorted(set(ilm_rules) - set(ilm_rules) | set(ilm_rules) - set(wiki_rules))

out = []
out.append("# PEG morphology: wiki page vs ilmentufa camxes.peg")
out.append("")
out.append("Generated by `tests/gen-peg-diff.py` (see its docstring for the exact method). Do not edit by hand.")
out.append("")
out.append(f"- Wiki page: BPFK Section: PEG Morphology Algorithm, revid {page['revid']} ({page['timestamp']}), sha256 {page['source_sha256']}, from the mw.lojban.org mirror fetched {snap['fetchedAt']}.")
out.append(f"- ilmentufa: camxes.peg @ {ilm_head}.")
out.append("")
out.append(f"Rules present in both with differing normalized bodies ({len(diff)}):")
out.append("")
out.append("```")
for n, w, i in diff:
    out.append(f"RULE: {n}\n  wiki:  {w}\n  ilmen: {i}\n")
out.append("```")
out.append("")
out.append(f"Present only in the wiki text: {len(only_wiki)} rules (the page's cmavo-classification section — selma'o definitions — plus historical alternates kept as comments are excluded by the comment filter).")
out.append(f"Present only in ilmentufa: {len(only_ilm)} rules (implementation additions such as spaces/comma handling and the syntax grammar's terminals).")
out.append("")
out.append("Assessment (from the CLL-update research, consensus-reviewed): naming (cmene→cmevla in `cmavo`/`final_syllable`/`lojban_word`), a `jbocme` bugfix (`*`→`+`), glide-aware `stress`, consonantal syllables allowed in `stressed_fuhivla_rafsi`, a `y` lookahead fix, the brivla/lujvo rule refactor (`brivla`+`lujvo` merged into `brivla <- !cmavo initial_rafsi* brivla_core`), plus two inconsequential textual differences in cmavo classification (`BY`: ybu moved inside the lookahead group; `FAhA`: a doubled `&post_word` in ilmentufa) — substantively the same morphology. Both incorporate the CGV ban (`onset <- h / glide / initial`) and dotside.")
out.append("")
print("\n".join(out))
